version: "3.2"

networks:
   frontend:
   backend:

services:
   catalog:
      build:
         context: .\
         dockerfile: Dockerfile
      image: investips/securities
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=SecuritiesDB
         - DatabaseUser=sa
         - DatabaseUserPassword=MyComplexPassword!234
      container_name: securitiesapi
      ports:
         - "5000:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
         
   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1445:1433"

      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=MyComplexPassword!234
      networks:
         - backend

      