version: "3.2"

networks:
   frontend:
   backend:

services:
   catalog:
      build:
         context: .\
         dockerfile: Dockerfile
      image: cdcalderon/investipssecurities
      environment:
         - DatabaseServer=tcp:investips.database.windows.net
         - DatabaseName=investipssecurities
         - DatabaseUser=cdcalderon
         - DatabaseUserPassword=MyComplexPassword!234
      container_name: securitiesapi
      ports:
         - "5000:80"
      networks:
         - frontend